package com.puresoltechnologies.debugging.agent;

/**
 * This is a special class loader which is able to load generated byte code as
 * class.
 * 
 * @author Rick-Rainer Ludwig
 */
public class ByteCodeCassLoader extends ClassLoader {

    public Class<?> defineClass(String name, byte[] byteCode) {
	if (byteCode == null) {
	    throw new IllegalArgumentException("byteCode must not be null.");
	}
	return defineClass(name, byteCode, 0, byteCode.length);
    }

}