/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_puresoltechnologies_toolshed_jpcap_JPCap */

#ifndef _Included_com_puresoltechnologies_toolshed_jpcap_JPCap
#define _Included_com_puresoltechnologies_toolshed_jpcap_JPCap
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_puresoltechnologies_toolshed_jpcap_JPCap
 * Method:    pcapOpenLive
 * Signature: (Ljava/lang/String;III)J
 */
JNIEXPORT jlong JNICALL Java_com_puresoltechnologies_toolshed_jpcap_JPCap_pcapOpenLive
  (JNIEnv *, jclass, jstring, jint, jint, jint);

/*
 * Class:     com_puresoltechnologies_toolshed_jpcap_JPCap
 * Method:    pcapLookupDev
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_puresoltechnologies_toolshed_jpcap_JPCap_pcapLookupDev
  (JNIEnv *, jclass);

/*
 * Class:     com_puresoltechnologies_toolshed_jpcap_JPCap
 * Method:    pcapClose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_puresoltechnologies_toolshed_jpcap_JPCap_pcapClose
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
