/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_puresoltechnologies_toolshed_jpcap_JPCap */

#ifndef _Included_com_puresoltechnologies_toolshed_jpcap_JPCap
#define _Included_com_puresoltechnologies_toolshed_jpcap_JPCap
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_puresoltechnologies_toolshed_jpcap_JPCap
 * Method:    getVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_puresoltechnologies_toolshed_jpcap_JPCap_getVersion
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
