package com.puresol.uhura.lexer;

import java.io.Serializable;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.ConcurrentMap;

/**
 * This class keeps the meta information about all tokens generated by a lexer.
 * 
 * @author Rick-Rainer Ludwig
 * 
 */
public class TokenMetaInformation implements Serializable {

	private static final long serialVersionUID = 4992743487086731635L;

	private static final ConcurrentMap<Token, TokenMetaData> metaInformation = new ConcurrentHashMap<Token, TokenMetaData>();

	public void add(Token token, TokenMetaData metaData) {
		metaInformation.put(token, metaData);
	}

	public TokenMetaData getMetaData(Token token) {
		if (token == null) {
			return null;
		}
		return metaInformation.get(token);
	}

	public void println() {
		for (Token token : metaInformation.keySet()) {
			TokenMetaData metaData = metaInformation.get(token);
			System.out.println(metaData.toString());
		}
	}

}
