= Purifinity Installation Manual
:revnumber: {project-version}
:author: Rick-Rainer Ludwig
:email: ludwig@puresol-technologies.com
:homepage: http://purifinity.com
:encoding: UTF-8

.............................................................................
This manual contains all information for installation and configuration of
Purifinity.
.............................................................................

== Get Purifinity
Purifinity can be downloaded as binary distribution, ready for installation, 
or as a source package to be built from the latest source code.

=== Binary Distribution
The binary distribution are official releases which are tested and ready 
for installation. It is preferred to use this version for productive 
installations.

Purifinity {project-version} can be downloaded a Purifinity's website at
http://purifinity.com.

=== Source Code
Source code can be used to use the latest source version for testing or
development. To build Purifinity form source, Maven is needed in version
{maven-version} or later.

Download the source code from GitHub 
https://github.com/PureSolTechnologies/Purifinity. 

Change into root directory of source directory and build Purifinity on
command line via:

[source,shell]
$ mvn install

== Extract Purifinity
The distribution of Purifinity come as ZIP archive or gzipped TAR archive.
Extract with either

{project-version}

[source,shell,subs="attributes"]
$ unzip purifinity-{project-version}.zip

or

[source,shell,subs="attributes"]
$ tar xfz purifinity-{project-version}.tar.gz

== Configure Purifinity

=== Configure Hadoop

Open and check the content of the following files in the extraction directory:

* lib/hadoop-{hadoop-version}/etc/hadoop/core-site.xml
* lib/hadoop-{hadoop-version}/etc/hadoop/hdfs-site.xml
* lib/hadoop-{hadoop-version}/etc/hadoop/yarn-site.xml
* lib/hadoop-{hadoop-version}/etc/hadoop/mapred-site.xml

Check here for the correct URLs and directories.

TIP: When the full community version is used, only the directories in 
hdfs-site.xml are to be adapted.

=== Configure HBase

Open and check the content of the following files in the extraction directory:

* lib/hbase-{hbase-version}/conf/hbase-site.xml

TIP: When the full community version is used, only the directory in 
hbase-site.xml are to be adapted.

== Prepare a new Installation 

Only once for the first installation, run the following command to format the 
hadoop file system:

[source,shell,subs="attributes"]
$ lib/hadoop-{hadoop-version}/bin/hadoop namenode -format

CAUTION: If you run this command again all data already present in Hadoop
will be deleted!

== Start and Stop Database

Start data storage:

[source,shell]
$ bin/startDB.sh

Stop data storage:

[source,shell]
$ bin/stopDB.sh

== Create and Migrate Database 

[source,shell]
$ bin/migrateDB.sh

IMPORTANT: Before the schema creation or migration can be started, the
data storage needs to be started. 
 
== Start and Stop Purifinity

[source,shell]
$ bin/startServer.sh

IMPORTANT: Before Purifinity can be started, the data storage needs to 
be started and also the database schema needs to be created or migrated. 